# Numpy

![Numpy](numpy.jpg)

In [1]:
import sys
import numpy as np

## Basic Numpy Arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0, -5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[:2]

array([1, 2])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [10]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [12]:
print(b[[0, 2, -1]])

[0. 1. 2.]


## Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [18]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c

array(['a', 'b', 'c'], dtype='<U1')

In [21]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a': 1}, sys])

In [24]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

## Dimensions and shapes

In [29]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [30]:
A.shape

(2, 3)

In [31]:
A.ndim

2

In [32]:
A.size

6

In [33]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [5,6,4],
        [3,2,1]
    ]
])

In [34]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 5,  6,  4],
        [ 3,  2,  1]]])

In [35]:
B.shape

(2, 2, 3)

In [36]:
B.size

12

In [37]:
B.ndim

3

In [45]:
C = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4]
    ]
], dtype=object)

In [46]:
c.dtype

dtype('<U1')

In [47]:
C.shape

(2,)

In [48]:
C.ndim

1

In [49]:
type(C[0])

list

## Indexing and Slicing of Matrices